# -*- coding: utf-8 -*-
"""dummies1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LjhFB7C-AzqRHaGGUiPyW86isSy_Z7Hc
"""

credit_history = {
    '1':[1],
    '0':[0]
}

gender= {
    'Male':[1],
    'Female':[0]
}